from __future__ import annotations


EXPECTED_FILE_SYMBOLS = {
    "apps/admin-portal/src/index.tsx": (
        {
            "name": "AdminPortal",
            "kind": "function",
            "line_start": 5,
            "line_end": 12,
            "column_start": 1,
            "column_end": 2,
            "signature": "AdminPortal()",
        },
    ),
    "apps/api-server/src/index.ts": (
        {
            "name": "app",
            "kind": "constant",
            "line_start": 6,
            "line_end": 6,
            "column_start": 1,
            "column_end": 2,
            "signature": "const app",
        },
    ),
    "apps/web-app/src/index.tsx": (
        {
            "name": "App",
            "kind": "function",
            "line_start": 6,
            "line_end": 12,
            "column_start": 1,
            "column_end": 2,
            "signature": "App()",
        },
    ),
    "libs/auth-lib/src/index.ts": (
        {
            "name": "generateToken",
            "kind": "function",
            "line_start": 6,
            "line_end": 8,
            "column_start": 1,
            "column_end": 2,
            "signature": "generateToken(payload: any): string",
        },
        {
            "name": "hashPassword",
            "kind": "function",
            "line_start": 10,
            "line_end": 12,
            "column_start": 1,
            "column_end": 2,
            "signature": "hashPassword(password: string): Promise<string>",
        },
    ),
    "libs/data-access/src/index.ts": (
        {
            "name": "connectDatabase",
            "kind": "function",
            "line_start": 5,
            "line_end": 7,
            "column_start": 1,
            "column_end": 2,
            "signature": "connectDatabase(url: string): Promise<void>",
        },
        {
            "name": "getUserModel",
            "kind": "function",
            "line_start": 9,
            "line_end": 11,
            "column_start": 1,
            "column_end": 2,
            "signature": "getUserModel()",
        },
    ),
    "libs/logging-lib/src/index.ts": (
        {
            "name": "logger",
            "kind": "constant",
            "line_start": 4,
            "line_end": 8,
            "column_start": 1,
            "column_end": 2,
            "signature": "const logger",
        },
    ),
    "libs/metrics-lib/src/index.ts": (
        {
            "name": "createCounter",
            "kind": "function",
            "line_start": 6,
            "line_end": 11,
            "column_start": 1,
            "column_end": 2,
            "signature": "createCounter(name: string)",
        },
        {
            "name": "register",
            "kind": "constant",
            "line_start": 4,
            "line_end": 4,
            "column_start": 1,
            "column_end": 2,
            "signature": "const register",
        },
    ),
    "libs/shared-ui/src/index.tsx": (
        {
            "name": "Button",
            "kind": "function",
            "line_start": 4,
            "line_end": 6,
            "column_start": 1,
            "column_end": 2,
            "signature": "Button({ label }: { label: string })",
        },
    ),
    "modules/python-bridge/index.js": (),
    "modules/wasm-module/index.js": (),
    "packages/core/src/index.ts": (
        {
            "name": "Core",
            "kind": "class",
            "line_start": 1,
            "line_end": 13,
            "column_start": 1,
            "column_end": 2,
            "signature": "class Core",
        },
        {
            "name": "constructor",
            "kind": "constructor",
            "line_start": 4,
            "line_end": 6,
            "column_start": 3,
            "column_end": 4,
            "signature": "constructor(value: string)",
        },
        {
            "name": "getValue",
            "kind": "method",
            "line_start": 8,
            "line_end": 10,
            "column_start": 3,
            "column_end": 4,
            "signature": "getValue(): string",
        },
        {
            "name": "setValue",
            "kind": "method",
            "line_start": 12,
            "line_end": 14,
            "column_start": 3,
            "column_end": 4,
            "signature": "setValue(value: string): void",
        },
    ),
    "packages/api-client/src/index.ts": (
        {
            "name": "ApiClient",
            "kind": "class",
            "line_start": 5,
            "line_end": 16,
            "column_start": 1,
            "column_end": 2,
            "signature": "class ApiClient",
        },
        {
            "name": "baseUrl",
            "kind": "property",
            "line_start": 6,
            "line_end": 6,
            "column_start": 3,
            "column_end": 4,
            "signature": "baseUrl: string",
        },
        {
            "name": "constructor",
            "kind": "constructor",
            "line_start": 8,
            "line_end": 10,
            "column_start": 3,
            "column_end": 4,
            "signature": "constructor(baseUrl: string)",
        },
        {
            "name": "get",
            "kind": "method",
            "line_start": 12,
            "line_end": 15,
            "column_start": 3,
            "column_end": 4,
            "signature": "get(endpoint: string): Promise<any>",
        },
    ),
    "packages/config/src/index.ts": (
        {
            "name": "Config",
            "kind": "interface",
            "line_start": 3,
            "line_end": 6,
            "column_start": 1,
            "column_end": 2,
            "signature": "interface Config",
        },
        {
            "name": "loadConfig",
            "kind": "function",
            "line_start": 8,
            "line_end": 13,
            "column_start": 1,
            "column_end": 2,
            "signature": "loadConfig(): Config",
        },
    ),
    "packages/core/src/index.test.ts": (),
    "packages/data-models/src/index.ts": (
        {
            "name": "Product",
            "kind": "interface",
            "line_start": 8,
            "line_end": 12,
            "column_start": 1,
            "column_end": 2,
            "signature": "interface Product",
        },
        {
            "name": "User",
            "kind": "interface",
            "line_start": 3,
            "line_end": 6,
            "column_start": 1,
            "column_end": 2,
            "signature": "interface User",
        },
    ),
    "packages/utils/src/index.test.ts": (),
    "packages/utils/src/index.ts": (
        {
            "name": "formatString",
            "kind": "function",
            "line_start": 3,
            "line_end": 5,
            "column_start": 1,
            "column_end": 2,
            "signature": "formatString(value: string): string",
        },
        {
            "name": "processCore",
            "kind": "function",
            "line_start": 7,
            "line_end": 9,
            "column_start": 1,
            "column_end": 2,
            "signature": "processCore(core: Core): string",
        },
    ),
    "services/analytics/src/index.ts": (
        {
            "name": "Analytics",
            "kind": "class",
            "line_start": 4,
            "line_end": 11,
            "column_start": 1,
            "column_end": 2,
            "signature": "class Analytics",
        },
        {
            "name": "counter",
            "kind": "property",
            "line_start": 5,
            "line_end": 5,
            "column_start": 3,
            "column_end": 4,
            "signature": "counter",
        },
        {
            "name": "track",
            "kind": "method",
            "line_start": 7,
            "line_end": 10,
            "column_start": 3,
            "column_end": 4,
            "signature": "track(event: string): void",
        },
    ),
    "services/auth-service/src/index.ts": (
        {
            "name": "AuthService",
            "kind": "class",
            "line_start": 5,
            "line_end": 14,
            "column_start": 1,
            "column_end": 2,
            "signature": "class AuthService",
        },
        {
            "name": "authenticate",
            "kind": "method",
            "line_start": 6,
            "line_end": 13,
            "column_start": 3,
            "column_end": 4,
            "signature": "authenticate(username: string, password: string): Promise<string>",
        },
    ),
    "services/data-processor/src/index.ts": (
        {
            "name": "DataProcessor",
            "kind": "class",
            "line_start": 3,
            "line_end": 14,
            "column_start": 1,
            "column_end": 2,
            "signature": "class DataProcessor",
        },
        {
            "name": "constructor",
            "kind": "constructor",
            "line_start": 6,
            "line_end": 8,
            "column_start": 3,
            "column_end": 4,
            "signature": "constructor()",
        },
        {
            "name": "process",
            "kind": "method",
            "line_start": 10,
            "line_end": 13,
            "column_start": 3,
            "column_end": 4,
            "signature": "process(data: number[]): Promise<number[]>",
        },
        {
            "name": "wasmReady",
            "kind": "property",
            "line_start": 4,
            "line_end": 4,
            "column_start": 3,
            "column_end": 4,
            "signature": "wasmReady: Promise<void>",
        },
    ),
    "services/notification/src/index.ts": (
        {
            "name": "NotificationService",
            "kind": "class",
            "line_start": 3,
            "line_end": 7,
            "column_start": 1,
            "column_end": 2,
            "signature": "class NotificationService",
        },
        {
            "name": "send",
            "kind": "method",
            "line_start": 4,
            "line_end": 6,
            "column_start": 3,
            "column_end": 4,
            "signature": "send(user: User, message: string): void",
        },
    ),
    "tools/build-aggregator/src/index.ts": (
        {
            "name": "buildAll",
            "kind": "function",
            "line_start": 3,
            "line_end": 5,
            "column_start": 1,
            "column_end": 2,
            "signature": "buildAll()",
        },
    ),
}
